### ISSUE TITLE
Attribute error when converting psd file

### ISSUE THREAD

**Issue by msieprawski** [kyamagu/psd2svg#6]
```
psd2svg a.psd b.svg
Traceback (most recent call last):
  File "/home/msieprawski/.local/bin/psd2svg", line 11, in <module>
    sys.exit(main())
  File "/home/msieprawski/.local/lib/python2.7/site-packages/psd2svg/__main__.py", line 39, in main
    converter.convert(args.output)
  File "/home/msieprawski/.local/lib/python2.7/site-packages/psd2svg/convert.py", line 158, in convert
    self._add_group(self._psd.layers)
  File "/home/msieprawski/.local/lib/python2.7/site-packages/psd2svg/convert.py", line 222, in _add_group
    self._add_layer(layer)
  File "/home/msieprawski/.local/lib/python2.7/site-packages/psd2svg/convert.py", line 230, in _add_layer
    mask = self._add_mask_if_exist(layer)
  File "/home/msieprawski/.local/lib/python2.7/site-packages/psd2svg/convert.py", line 367, in _add_mask_if_exist
    mask_data = layer.mask_data
AttributeError: 'PixelLayer' object has no attribute 'mask_data
```

**Comment by kyamagu** [comment]
@msieprawski Hi, can you check if the latest version v0.1.0a5 gives you the same error? You can simply upgrade in pip:

    pip install --upgrade psd2svg
